version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: suasupersenha
    ports:
      - 3306:3306

volumes:
  db_data: